dist: xenial
sudo: required

language: go
go:
  - "1.13.1"
env:
  global:
    - PPS_BUCKETS=6
    - AUTH_BUCKETS=2
    - GOPROXY=https://proxy.golang.org
  matrix:
    - BUCKET=MISC
    # If you want to update the number of PPS or auth buckets, you'll neet to
    # update the value of PPS_BUCKETS or AUTH_BUCKETS above
    - BUCKET=ADMIN
    - BUCKET=AUTH1
    - BUCKET=AUTH2
    - BUCKET=PFS
    - BUCKET=PPS1
    - BUCKET=PPS2
    - BUCKET=PPS3
    - BUCKET=PPS4
    - BUCKET=PPS5
    - BUCKET=PPS6
    - BUCKET=EXAMPLES

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      # Go to some effort to make sure that we lint as soon as we know we're
      # operating on the right version of the code. Linting as quickly as
      # possible in the build step (even before we've installed docker) catches
      # a lot of errors that are otherwise buried deep in the Travis logs and
      # gives developers faster feedback than waiting ~20 minutes and then
      # digging through the logs.
      script: etc/testing/travis_build_check.sh && etc/testing/lint.sh && etc/testing/travis_install.sh && etc/testing/travis_build_stash.sh && etc/testing/travis_build.sh

before_install:
  # Get some insight into the system
  - top -b -n 1|head -n 20
  - uptime
  - uname -a
  - cat /proc/cpuinfo

# NB: Have to switch directories because travis_test_check_and_pull.sh moves
# the build dir out under our feet.
#
# NB: we install here (rather than in a global install: branch) so that we can
# do stuff (like linting) in the build step before doing the slow install step
# (we don't need docker to lint the code).
script: etc/testing/travis_install.sh && etc/testing/travis_test_check_and_pull.sh && cd /home/travis/gopath/src/github.com/pachyderm/pachyderm && travis_retry bash -c 'timeout 20m etc/testing/travis.sh; status=$?; if [ "$status" -ne 0 ]; then etc/testing/kube_debug.sh; fi; exit $status'

notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
branches:
  only:
  # Trigger only for PR's to master
  - master
  # Trigger CI tests for all release branches
  # Eg. 1.9.x, 1.10.x
  - /^\d+\.\d+\.x/
  # Trigger CI tests for all branches that end with "-ci-trigger"
  # ruby reg-ex except for things before/after "/"
  - /.*(?i:ci-trigger)$/
  # For all branches uncomment the line below or remove the "branches" section
  #- /.*/
